import { prisma } from '../lib/prisma'
import { defaultRepsFromRepRange } from '../lib/rep-range'

export type SuggestedExercise = {
  exerciseId: string
  name: string
  movementPattern: string
  primaryMuscle: string | null
  equipment: string | null
  sets: number
  repRange: string
  restSeconds: number
  /** AI-calculated starting weight in kg. 0 = bodyweight / no load. User can adjust in tracker. */
  suggestedWeightKg: number
  /** Where the suggested weight came from (for explainability + UI hints). */
  weightSource: 'history' | 'heuristic' | 'bodyweight'
  /** One-sentence explanation of why THIS exercise fits the user's stated
   *  goal. Generated by the AI alongside the pick. Undefined when no
   *  rationale was returned (older sessions, AI omitted it). */
  whyThisExercise?: string
}

// ─── Suggested weight heuristic ──────────────────────────────────────────────
const PATTERN_BW_FACTOR: Record<string, number> = {
  squat: 0.95,
  squat_unilateral: 0.40,
  hinge: 1.25,
  hinge_unilateral: 0.45,
  push_horizontal: 0.80,
  push_horizontal_unilateral: 0.30,
  push_vertical: 0.50,
  push_vertical_unilateral: 0.20,
  pull_horizontal: 0.65,
  pull_horizontal_unilateral: 0.25,
  pull_vertical: 0.0,
  isolation: 0.12,
  carry: 0.50,
  core: 0.0,
  skill_stability: 0.10,
}

const LEVEL_FACTOR: Record<string, number> = {
  beginner: 0.50,
  intermediate: 1.00,
  advanced: 1.25,
}

export function roundToStep(value: number, step = 2.5): number {
  return Math.round(value / step) * step
}

export function heuristicWeightKg(opts: {
  pattern: string
  equipment: string | null
  bodyweightKg: number | null
  trainingLevel: string | null
}): number {
  const baseFactor = PATTERN_BW_FACTOR[opts.pattern] ?? 0.30
  if (baseFactor === 0) return 0
  const bw = opts.bodyweightKg ?? 75
  const level = (opts.trainingLevel ?? 'beginner').toLowerCase()
  const lvl = LEVEL_FACTOR[level] ?? 0.50
  let w = bw * baseFactor * lvl
  const eq = (opts.equipment ?? '').toLowerCase()
  if (eq.includes('bodyweight') || eq === 'none' || eq === '') return 0
  if (eq.includes('dumbbell')) w *= 0.40
  else if (eq.includes('kettlebell')) w *= 0.45
  else if (eq.includes('machine') || eq.includes('cable')) w *= 0.65
  const rounded = roundToStep(w, 2.5)
  return Math.min(Math.max(rounded, 5), 300)
}

/** Most recent completed WORK-set weight per exerciseId (for warm starts on repeated lifts). */
export async function fetchLastWorkingWeights(
  userId: string,
  exerciseIds: string[],
): Promise<Map<string, number>> {
  if (exerciseIds.length === 0) return new Map()
  const recent = await prisma.workoutSet.findMany({
    where: {
      tag: 'WORK',
      isCompleted: true,
      weightKg: { gt: 0 },
      workoutExercise: {
        exerciseId: { in: exerciseIds },
        workout: { userId, status: { in: ['completed', 'posted'] } },
      },
    },
    select: {
      weightKg: true,
      createdAt: true,
      workoutExercise: { select: { exerciseId: true } },
    },
    orderBy: { createdAt: 'desc' },
    take: 400,
  })
  const out = new Map<string, number>()
  for (const s of recent) {
    const eid = s.workoutExercise.exerciseId
    if (!out.has(eid)) out.set(eid, Number(s.weightKg))
    if (out.size === exerciseIds.length) break
  }
  return out
}

export type WorkoutSuggestionResult = {
  blueprintId: string
  title: string
  description: string
  primaryGoal: string | null
  exercises: SuggestedExercise[]
  warnings: string[]
}

export async function createDraftWorkoutFromSuggestion(
  userId: string,
  suggestion: WorkoutSuggestionResult,
): Promise<{
  workout: unknown
  meta: { blueprintId: string; warnings: string[] }
}> {
  if (suggestion.exercises.length === 0) {
    throw new Error('NO_EXERCISES')
  }

  const workout = await prisma.$transaction(async (tx) => {
    const w = await tx.workout.create({
      data: {
        userId,
        status: 'draft',
        notes: `Suggested: ${suggestion.title} (${suggestion.blueprintId})`,
      },
    })
    for (let i = 0; i < suggestion.exercises.length; i++) {
      const ex = suggestion.exercises[i]
      const we = await tx.workoutExercise.create({
        data: {
          workoutId: w.id,
          exerciseId: ex.exerciseId,
          position: i,
          restSecondsDefault: ex.restSeconds,
          repRangeHint: ex.repRange,
        },
      })
      const defaultReps = defaultRepsFromRepRange(ex.repRange)
      const startingWeight = Number.isFinite(ex.suggestedWeightKg) && ex.suggestedWeightKg >= 0
        ? ex.suggestedWeightKg
        : 0
      for (let si = 0; si < ex.sets; si++) {
        await tx.workoutSet.create({
          data: {
            workoutExerciseId: we.id,
            setIndex: si,
            weightKg: startingWeight,
            reps: defaultReps,
            tag: 'WORK',
            isCompleted: false,
          },
        })
      }
    }
    return w
  })

  const full = await prisma.workout.findFirst({
    where: { id: workout.id, userId },
    include: {
      exercises: {
        include: { exercise: true, sets: { orderBy: { setIndex: 'asc' } } },
        orderBy: { position: 'asc' },
      },
    },
  })

  await prisma.analyticsEvent.create({
    data: {
      userId,
      eventName: 'workout_from_suggestion',
      props: { blueprintId: suggestion.blueprintId },
    },
  })

  return {
    workout: full,
    meta: { blueprintId: suggestion.blueprintId, warnings: suggestion.warnings },
  }
}

/** Shown when the user's goal mentions an injury/pain. Not medical advice. */
export const INJURY_SAFETY_WARNING =
  'You mentioned an injury or pain, so this plan is kept conservative. This is not medical advice — start light, skip anything that hurts, and check with a healthcare professional before loading the affected area.'

/** Planning uses DeepSeek — see `ai-workout-suggestion.service.ts`. */
export async function generateWorkoutSuggestionForUser(
  userId: string,
  opts?: { refresh?: boolean },
): Promise<WorkoutSuggestionResult> {
  const { getCachedWorkoutSuggestion, setCachedWorkoutSuggestion } = await import(
    './workout-suggestion-cache.service'
  )

  if (!opts?.refresh) {
    const cached = await getCachedWorkoutSuggestion(userId)
    if (cached) return cached
  }

  const det = await import('./deterministic-workout.service')
  const { hasInjuryContext } = await import('../lib/goal-guidance')

  // Read the goal text once so any path can be decorated with a safety warning.
  const tp = await prisma.userTrainingProfile.findUnique({
    where: { userId },
    select: { onboardingGoalText: true },
  })
  const injury = hasInjuryContext(tp?.onboardingGoalText)

  // Cache + (when the goal mentions an injury) attach a non-medical safety
  // disclaimer the UI surfaces. The plan is kept conservative server-side, but
  // we never pretend to be rehab guidance.
  const finish = async (r: WorkoutSuggestionResult): Promise<WorkoutSuggestionResult> => {
    if (injury && !r.warnings.includes(INJURY_SAFETY_WARNING)) {
      r.warnings = [INJURY_SAFETY_WARNING, ...r.warnings]
    }
    await setCachedWorkoutSuggestion(userId, r)
    return r
  }

  // (1) Deterministic-first: goals covered by a blueprint (common buckets incl.
  // jump/explosive) → compose from the tagged catalog. Instant, no LLM.
  try {
    const r = await det.generateDeterministicSuggestion(userId)
    if (r) return finish(r)
  } catch {
    /* non-fatal → try next path */
  }

  // (2) Niche goals → LLM DECOMPOSES the goal into pattern slots (constrained to
  // our vocabulary, no exercise names), then the same composer fills them from
  // the catalog. Handles e.g. "table tennis" without hallucination.
  try {
    const r = await det.generateDecomposedSuggestion(userId)
    if (r) return finish(r)
  } catch {
    /* non-fatal → try next path */
  }

  // (3) Last resort: the full free-form LLM generator.
  const { generateAiWorkoutSuggestionForUser } = await import('./ai-workout-suggestion.service')
  const fresh = await generateAiWorkoutSuggestionForUser(userId)
  return finish(fresh)
}
