// ignore_for_file: constant_identifier_names
// GENERATED — app-wide icon set mapped to Flaticon UIcons (bold rounded).
// Each entry is a const IconData literal (codepoint + bundled font) so it
// works inside const Icon(...) without breaking const-ness. Names mirror the
// UIcons catalog. Icons by Flaticon (https://www.flaticon.com/uicons).
//
// Do not hand-edit; regenerate from tool/uicons_icon_map.tsv if the icon set changes.
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const String _f = 'uicons_bold_rounded';
  static const IconData angle_small_down = IconData(0xe91c, fontFamily: _f, fontPackage: _f);
  static const IconData angle_small_left = IconData(0xe91d, fontFamily: _f, fontPackage: _f);
  static const IconData angle_small_right = IconData(0xe91e, fontFamily: _f, fontPackage: _f);
  static const IconData angle_small_up = IconData(0xe91f, fontFamily: _f, fontPackage: _f);
  static const IconData apps = IconData(0xe927, fontFamily: _f, fontPackage: _f);
  static const IconData arrow_small_down = IconData(0xe954, fontFamily: _f, fontPackage: _f);
  static const IconData arrow_small_left = IconData(0xe955, fontFamily: _f, fontPackage: _f);
  static const IconData arrow_small_right = IconData(0xe956, fontFamily: _f, fontPackage: _f);
  static const IconData arrow_small_up = IconData(0xe957, fontFamily: _f, fontPackage: _f);
  static const IconData arrow_trend_down = IconData(0xe964, fontFamily: _f, fontPackage: _f);
  static const IconData arrow_trend_up = IconData(0xe965, fontFamily: _f, fontPackage: _f);
  static const IconData arrow_up_right_from_square = IconData(0xe96c, fontFamily: _f, fontPackage: _f);
  static const IconData arrows_repeat = IconData(0xe95c, fontFamily: _f, fontPackage: _f);
  static const IconData badge_check = IconData(0xe97b, fontFamily: _f, fontPackage: _f);
  static const IconData balance_scale_left = IconData(0xe981, fontFamily: _f, fontPackage: _f);
  static const IconData ban = IconData(0xe985, fontFamily: _f, fontPackage: _f);
  static const IconData barcode_scan = IconData(0xe98b, fontFamily: _f, fontPackage: _f);
  static const IconData bell = IconData(0xe994, fontFamily: _f, fontPackage: _f);
  static const IconData bell_ring = IconData(0xe995, fontFamily: _f, fontPackage: _f);
  static const IconData bike = IconData(0xe997, fontFamily: _f, fontPackage: _f);
  static const IconData bolt = IconData(0xe99f, fontFamily: _f, fontPackage: _f);
  static const IconData book = IconData(0xe9a0, fontFamily: _f, fontPackage: _f);
  static const IconData bookmark = IconData(0xe9a5, fontFamily: _f, fontPackage: _f);
  static const IconData boxing_glove = IconData(0xe9b3, fontFamily: _f, fontPackage: _f);
  static const IconData brain_circuit = IconData(0xe9b6, fontFamily: _f, fontPackage: _f);
  static const IconData bug = IconData(0xe9be, fontFamily: _f, fontPackage: _f);
  static const IconData bulb = IconData(0xe9c0, fontFamily: _f, fontPackage: _f);
  static const IconData cake_birthday = IconData(0xe9c9, fontFamily: _f, fontPackage: _f);
  static const IconData calendar = IconData(0xe9cc, fontFamily: _f, fontPackage: _f);
  static const IconData calendar_check = IconData(0xe9cd, fontFamily: _f, fontPackage: _f);
  static const IconData camera = IconData(0xe9db, fontFamily: _f, fontPackage: _f);
  static const IconData chart_histogram = IconData(0xea06, fontFamily: _f, fontPackage: _f);
  static const IconData chart_line_up = IconData(0xea07, fontFamily: _f, fontPackage: _f);
  static const IconData check = IconData(0xea11, fontFamily: _f, fontPackage: _f);
  static const IconData circle = IconData(0xea29, fontFamily: _f, fontPackage: _f);
  static const IconData clock = IconData(0xea32, fontFamily: _f, fontPackage: _f);
  static const IconData cloud = IconData(0xea49, fontFamily: _f, fontPackage: _f);
  static const IconData cloud_check = IconData(0xea4a, fontFamily: _f, fontPackage: _f);
  static const IconData cloud_disabled = IconData(0xea4b, fontFamily: _f, fontPackage: _f);
  static const IconData cloud_download = IconData(0xea4c, fontFamily: _f, fontPackage: _f);
  static const IconData cloud_upload = IconData(0xea5f, fontFamily: _f, fontPackage: _f);
  static const IconData comment_alt = IconData(0xea73, fontFamily: _f, fontPackage: _f);
  static const IconData comments = IconData(0xea83, fontFamily: _f, fontPackage: _f);
  static const IconData cross_circle = IconData(0xea9c, fontFamily: _f, fontPackage: _f);
  static const IconData cross_small = IconData(0xea9d, fontFamily: _f, fontPackage: _f);
  static const IconData crown = IconData(0xea9e, fontFamily: _f, fontPackage: _f);
  static const IconData delete_user = IconData(0xeaaf, fontFamily: _f, fontPackage: _f);
  static const IconData disk = IconData(0xeac3, fontFamily: _f, fontPackage: _f);
  static const IconData document = IconData(0xeac7, fontFamily: _f, fontPackage: _f);
  static const IconData download = IconData(0xeacc, fontFamily: _f, fontPackage: _f);
  static const IconData edit = IconData(0xead6, fontFamily: _f, fontPackage: _f);
  static const IconData envelope = IconData(0xeadd, fontFamily: _f, fontPackage: _f);
  static const IconData exclamation = IconData(0xeaea, fontFamily: _f, fontPackage: _f);
  static const IconData eye = IconData(0xeaef, fontFamily: _f, fontPackage: _f);
  static const IconData eye_crossed = IconData(0xeaf0, fontFamily: _f, fontPackage: _f);
  static const IconData filter_slash = IconData(0xeb09, fontFamily: _f, fontPackage: _f);
  static const IconData flag = IconData(0xeb0c, fontFamily: _f, fontPackage: _f);
  static const IconData flame = IconData(0xeb0f, fontFamily: _f, fontPackage: _f);
  static const IconData globe = IconData(0xeb3b, fontFamily: _f, fontPackage: _f);
  static const IconData grin = IconData(0xeb47, fontFamily: _f, fontPackage: _f);
  static const IconData gym = IconData(0xeb55, fontFamily: _f, fontPackage: _f);
  static const IconData heart = IconData(0xeb64, fontFamily: _f, fontPackage: _f);
  static const IconData home = IconData(0xeb6d, fontFamily: _f, fontPackage: _f);
  static const IconData inbox = IconData(0xeb7b, fontFamily: _f, fontPackage: _f);
  static const IconData info = IconData(0xeb81, fontFamily: _f, fontPackage: _f);
  static const IconData interrogation = IconData(0xeb84, fontFamily: _f, fontPackage: _f);
  static const IconData leaf = IconData(0xeba0, fontFamily: _f, fontPackage: _f);
  static const IconData link = IconData(0xebab, fontFamily: _f, fontPackage: _f);
  static const IconData list = IconData(0xebb3, fontFamily: _f, fontPackage: _f);
  static const IconData location_alt = IconData(0xebb6, fontFamily: _f, fontPackage: _f);
  static const IconData lock = IconData(0xebb7, fontFamily: _f, fontPackage: _f);
  static const IconData map = IconData(0xebc2, fontFamily: _f, fontPackage: _f);
  static const IconData megaphone = IconData(0xebcc, fontFamily: _f, fontPackage: _f);
  static const IconData menu_dots = IconData(0xebd1, fontFamily: _f, fontPackage: _f);
  static const IconData menu_dots_vertical = IconData(0xebd2, fontFamily: _f, fontPackage: _f);
  static const IconData minus = IconData(0xebd8, fontFamily: _f, fontPackage: _f);
  static const IconData moon = IconData(0xebe5, fontFamily: _f, fontPackage: _f);
  static const IconData mountains = IconData(0xebe8, fontFamily: _f, fontPackage: _f);
  static const IconData navigation = IconData(0xebf4, fontFamily: _f, fontPackage: _f);
  static const IconData paper_plane = IconData(0xec08, fontFamily: _f, fontPackage: _f);
  static const IconData pause = IconData(0xec0a, fontFamily: _f, fontPackage: _f);
  static const IconData percentage = IconData(0xec13, fontFamily: _f, fontPackage: _f);
  static const IconData picture = IconData(0xec1e, fontFamily: _f, fontPackage: _f);
  static const IconData play = IconData(0xec27, fontFamily: _f, fontPackage: _f);
  static const IconData plus = IconData(0xec2b, fontFamily: _f, fontPackage: _f);
  static const IconData quote_right = IconData(0xec41, fontFamily: _f, fontPackage: _f);
  static const IconData refresh = IconData(0xec54, fontFamily: _f, fontPackage: _f);
  static const IconData restaurant = IconData(0xec5b, fontFamily: _f, fontPackage: _f);
  static const IconData ruler_horizontal = IconData(0xec69, fontFamily: _f, fontPackage: _f);
  static const IconData ruler_vertical = IconData(0xec6b, fontFamily: _f, fontPackage: _f);
  static const IconData running = IconData(0xec6c, fontFamily: _f, fontPackage: _f);
  static const IconData salad = IconData(0xec75, fontFamily: _f, fontPackage: _f);
  static const IconData search = IconData(0xec7f, fontFamily: _f, fontPackage: _f);
  static const IconData settings = IconData(0xec89, fontFamily: _f, fontPackage: _f);
  static const IconData settings_sliders = IconData(0xec8a, fontFamily: _f, fontPackage: _f);
  static const IconData share = IconData(0xec8b, fontFamily: _f, fontPackage: _f);
  static const IconData shield_check = IconData(0xec8e, fontFamily: _f, fontPackage: _f);
  static const IconData shield_plus = IconData(0xec91, fontFamily: _f, fontPackage: _f);
  static const IconData sign_out_alt = IconData(0xeca5, fontFamily: _f, fontPackage: _f);
  static const IconData sparkles = IconData(0xeccc, fontFamily: _f, fontPackage: _f);
  static const IconData square = IconData(0xecd1, fontFamily: _f, fontPackage: _f);
  static const IconData star = IconData(0xecd6, fontFamily: _f, fontPackage: _f);
  static const IconData stop = IconData(0xecdf, fontFamily: _f, fontPackage: _f);
  static const IconData stopwatch = IconData(0xece0, fontFamily: _f, fontPackage: _f);
  static const IconData sun = IconData(0xece7, fontFamily: _f, fontPackage: _f);
  static const IconData swimmer = IconData(0xecee, fontFamily: _f, fontPackage: _f);
  static const IconData tachometer_fast = IconData(0xecff, fontFamily: _f, fontPackage: _f);
  static const IconData target = IconData(0xed06, fontFamily: _f, fontPackage: _f);
  static const IconData time_past = IconData(0xed24, fontFamily: _f, fontPackage: _f);
  static const IconData trash = IconData(0xed39, fontFamily: _f, fontPackage: _f);
  static const IconData trophy = IconData(0xed3f, fontFamily: _f, fontPackage: _f);
  static const IconData user = IconData(0xed57, fontFamily: _f, fontPackage: _f);
  static const IconData user_add = IconData(0xed58, fontFamily: _f, fontPackage: _f);
  static const IconData users = IconData(0xed59, fontFamily: _f, fontPackage: _f);
  static const IconData water_bottle = IconData(0xed6d, fontFamily: _f, fontPackage: _f);
  static const IconData wind = IconData(0xed75, fontFamily: _f, fontPackage: _f);
}
