// File generated by FlutterFire CLI can replace this file entirely.
// Until then: run `flutterfire configure` or paste values from Firebase Console
// (Project settings → Your apps → SDK setup).
//
// iOS setup (one-time):
//   1. Add iOS app in Firebase Console → Project settings
//   2. Download GoogleService-Info.plist → place in ios/Runner/
//   3. Run `flutterfire configure` to auto-fill values below
//   4. In Xcode: ensure GoogleService-Info.plist is in Runner target
//
// Debug without FCM (avoids second engine + network at startup):
//   flutter run --dart-define=DISABLE_FCM=true

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// `true` → skip FCM background handler and don't start push in app (performance testing).
const bool kFirebaseMessagingDisabled =
    bool.fromEnvironment('DISABLE_FCM', defaultValue: false);

/// `true` when [projectId] is set for the current platform (real keys in code).
class DefaultFirebaseOptions {
  static bool get isConfigured {
    if (kIsWeb) return false;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android.projectId.isNotEmpty &&
            android.apiKey.isNotEmpty &&
            !android.apiKey.startsWith('REPLACE_');
      case TargetPlatform.iOS:
        return ios.projectId.isNotEmpty &&
            ios.apiKey.isNotEmpty &&
            ios.appId.isNotEmpty &&
            !ios.apiKey.startsWith('REPLACE_') &&
            !ios.appId.startsWith('REPLACE_');
      default:
        return false;
    }
  }

  /// Push: project OK and not explicitly disabled with `--dart-define=DISABLE_FCM=true`.
  static bool get fcmEnabled => isConfigured && !kFirebaseMessagingDisabled;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
          'Firebase messaging is not used on web in this project.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('FCM: only Android and iOS supported.');
    }
  }

  /// Align with `android/app/google-services.json` after `flutterfire configure`.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRFbT_cR2BrzREyvcQ00PsMKNX_U05rs',
    appId: '1:715817017339:android:27b404694ea74b9f77b55e',
    messagingSenderId: '715817017339',
    projectId: 'zvelt-3998a',
    storageBucket: 'zvelt-3998a.firebasestorage.app',
  );

  /// iOS Firebase options — MUST be filled before releasing on iOS.
  ///
  /// Steps:
  ///   1. Open https://console.firebase.google.com → zvelt-3998a → Project settings
  ///   2. Click "Add app" → iOS → bundle ID: com.lunaoscar.zvelt
  ///   3. Download GoogleService-Info.plist → place in ios/Runner/
  ///   4. Run `flutterfire configure` which auto-generates this file
  ///   5. Copy the iOS values below (or let flutterfire overwrite this whole file)
  ///
  /// Without these, push notifications will NOT work on iOS.
  /// The app will still run — FCM is skipped gracefully when [isConfigured] is false.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID'),
    messagingSenderId: '715817017339',
    projectId: 'zvelt-3998a',
    storageBucket: 'zvelt-3998a.firebasestorage.app',
    iosBundleId: 'com.lunaoscar.zvelt',
  );
}
